# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
- pre-commit
- commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: detect-private-key
    # -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
        args: [--fix=no]
    -   id: trailing-whitespace
    -   id: check-toml
-   repo: https://github.com/Vimjas/vint
    rev: v0.4a3
    hooks:
    - id: vint
      args: ['--style-problem', '--no-color', '-f', '{file_path}:{line_number}:{column_number}:{severity}:{description} ({policy_name})']
